// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9JVAegWvU9Kj45h0pnGWvXufjPrsSJDE',
    appId: '1:403715462829:android:0bf5d935451b4dba279824',
    messagingSenderId: '403715462829',
    projectId: 'group-7-final-project-2f7e5',
    databaseURL: 'https://group-7-final-project-2f7e5-default-rtdb.firebaseio.com',
    storageBucket: 'group-7-final-project-2f7e5.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGzDvFrKdyuL8DO5JRw8MEiq93Aw9kRxM',
    appId: '1:403715462829:web:a58ffa05f5c4a180279824',
    messagingSenderId: '403715462829',
    projectId: 'group-7-final-project-2f7e5',
    authDomain: 'group-7-final-project-2f7e5.firebaseapp.com',
    databaseURL: 'https://group-7-final-project-2f7e5-default-rtdb.firebaseio.com',
    storageBucket: 'group-7-final-project-2f7e5.appspot.com',
    measurementId: 'G-TJ2RWXX7P2',
  );

}